[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  autoLaunch = true
  command = "npm run dev"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-sitemap"

# Redirect from Netlify subdomain to custom domain
[[redirects]]
  from = "https://wyshai.netlify.app/*"
  to = "https://wyshai.com/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "www.wyshai.com/*"
  to = "https://wyshai.com/:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache headers for static assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Pre-rendering configuration
[prerendering]
  enabled = true
  crawl = true
  force_prerender = false
  ignore_query = true
